/**
 * conversationSummarizer.ts — PrivateAI Smart Summarization
 *
 * Phase 1: Auto-generates conversation summaries after each exchange.
 * Uses Claude Haiku (fast, cheap) to extract:
 * - Highlights (3-5 key points)
 * - Hard-stick notes (important decisions/findings)
 * - Action items (with status: done/pending/blocked)
 * - Files referenced
 * - Knowledge graph nodes
 * - Time spent & message count
 *
 * Stores in SQLite with user control fields (pinned, tags, keepUntil, archivedToCloud)
 */

import Constants from 'expo-constants';
import { openDatabaseAsync } from 'expo-sqlite';

const CLAUDE_HAIKU_MODEL = 'claude-haiku-4-5-20251001';
const CLAUDE_API_URL = 'https://api.anthropic.com/v1/messages';

// ─────────────────────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────────────────────

export interface ActionItem {
  task: string;
  status: 'done' | 'pending' | 'blocked';
  dueDate?: string;
}

export interface ConversationSummary {
  id: string;
  conversationId: string;
  date: string;                    // ISO timestamp
  subject: string;                 // Auto-detected category
  
  // Core summaries (auto-generated by Haiku)
  highlights: string[];            // 3-5 key bullets
  hardStickNotes: string[];        // Critical decisions/findings
  actionItems: ActionItem[];       // Tasks with status
  
  // Metadata
  filesReferenced: string[];
  knowledgeGraphNodes: string[];
  estimatedTimeSpent: number;      // minutes
  messageCount: number;
  
  // User control
  pinnedForReview: boolean;
  userTags: string[];
  keepUntil?: string;              // User-set retention date
  archivedToCloud?: string;        // Timestamp when moved to cloud
}

export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface SummaryData {
  highlights: string[];
  hardStickNotes: string[];
  actionItems: ActionItem[];
  filesReferenced: string[];
  estimatedTimeSpent: number;
}

/** Raw row shape from the conversation_summaries SQLite table. */
interface SummaryRow {
  id: string;
  conversation_id: string;
  date: string;
  subject: string;
  highlights: string;
  hard_stick_notes: string;
  action_items: string;
  files_referenced: string;
  kg_nodes: string;
  time_spent: number;
  message_count: number;
  pinned: number;
  user_tags: string;
  keep_until: string | null;
  archived_to_cloud: string | null;
}
// ─────────────────────────────────────────────────────────────
// DATABASE SETUP
// ─────────────────────────────────────────────────────────────

let _db: any = null;

async function getDatabase() {
  if (_db) return _db;
  try {
    _db = await openDatabaseAsync('privateai.db');
    
    // Create conversation_summaries table if not exists
    await _db.execAsync(`
      CREATE TABLE IF NOT EXISTS conversation_summaries (
        id TEXT PRIMARY KEY,
        conversation_id TEXT NOT NULL,
        date TEXT NOT NULL,
        subject TEXT,
        highlights TEXT,                 -- JSON array
        hard_stick_notes TEXT,            -- JSON array
        action_items TEXT,                -- JSON array
        files_referenced TEXT,            -- JSON array
        kg_nodes TEXT,                    -- JSON array
        time_spent INTEGER,
        message_count INTEGER,
        pinned BOOLEAN DEFAULT 0,
        user_tags TEXT,                   -- JSON array
        keep_until TEXT,
        archived_to_cloud TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    console.log('[SummaryDB] Table ready');
    return _db;
  } catch (e) {
    console.error('[SummaryDB] init error:', e);
    throw e;
  }
}

// ─────────────────────────────────────────────────────────────
// SUBJECT DETECTION
// ─────────────────────────────────────────────────────────────

export function detectSubject(messages: ConversationMessage[]): string {
  const text = messages.map(m => m.content).join(' ').toLowerCase();
  
  const subjects: Record<string, string[]> = {
    'PrivateAI Development': ['privateai', 'architecture', 'router', 'model', 'llama', 'integration', 'agent', 'indexing', 'summariz'],
    'Personal Notes': ['note', 'remember', 'idea', 'thought', 'personal', 'random'],
    'Research': ['research', 'explore', 'investigate', 'study', 'learn', 'understand', 'analysis'],
    'Project Work': ['project', 'build', 'implement', 'develop', 'work', 'feature', 'bug fix'],
    'Medical': ['health', 'medical', 'appointment', 'symptom', 'medication', 'doctor'],
  };
  
  let bestMatch = 'General';
  let bestScore = 0;
  
  for (const [subject, keywords] of Object.entries(subjects)) {
    const score = keywords.filter(kw => text.includes(kw)).length;
    if (score > bestScore) {
      bestMatch = subject;
      bestScore = score;
    }
  }
  
  return bestMatch;
}
// ─────────────────────────────────────────────────────────────
// HAIKU SUMMARIZATION
// ─────────────────────────────────────────────────────────────

export async function generateSummaryData(
  messages: ConversationMessage[],
  apiKey: string
): Promise<SummaryData> {
  if (!apiKey) {
    throw new Error('Claude API key not configured');
  }

  // Build conversation text
  const conversationText = messages
    .map(m => `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.content}`)
    .join('\n\n');

  const systemPrompt = `You are a conversation summarizer. Respond ONLY with valid JSON. No markdown, no code blocks, no explanation. Start your response with { and end with }.`;

  const userPrompt = `Summarize this conversation as JSON with this exact structure:
{"highlights":["point1","point2","point3"],"hardStickNotes":["note1"],"actionItems":[{"task":"description","status":"pending"}],"filesReferenced":[],"estimatedTimeSpent":5}

Rules:
- highlights: 3-5 key points discussed
- hardStickNotes: critical decisions or must-remember items (can be empty array)
- actionItems: tasks with status "done", "pending", or "blocked" (can be empty array)
- filesReferenced: any filenames mentioned (can be empty array)
- estimatedTimeSpent: conversation length in minutes (number)

Conversation:
${conversationText}`;

  try {
    const res = await fetch(CLAUDE_API_URL, {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: CLAUDE_HAIKU_MODEL,
        max_tokens: 800,
        system: systemPrompt,
        messages: [
          {
            role: 'user',
            content: userPrompt,
          },
          {
            role: 'assistant',
            content: '{',
          },
        ],
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Haiku API error ${res.status}: ${err}`);
    }

    const data = await res.json();
    const rawText = data?.content?.[0]?.text ?? '';
    // Prepend the '{' we used as prefill
    const responseText = '{' + rawText;

    console.log('[Summarizer] Raw Haiku response (first 300 chars):', responseText.slice(0, 300));
    console.log('[Summarizer] Stop reason:', data?.stop_reason, 'Content blocks:', data?.content?.length);

    // Try to parse JSON from response
    let parsed: any = null;

    // Attempt 1: Extract JSON object from { to }
    try {
      let jsonStr = responseText.trim();
      jsonStr = jsonStr.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/, '');
      const firstBrace = jsonStr.indexOf('{');
      const lastBrace = jsonStr.lastIndexOf('}');
      if (firstBrace !== -1 && lastBrace > firstBrace) {
        jsonStr = jsonStr.slice(firstBrace, lastBrace + 1);
      }
      parsed = JSON.parse(jsonStr);
    } catch (parseErr) {
      console.warn('[Summarizer] JSON parse attempt 1 failed:', (parseErr as Error).message);
    }

    // Attempt 2: If truncated, try closing the JSON manually
    if (!parsed) {
      try {
        let fixedJson = responseText.trim();
        // Remove markdown fences
        fixedJson = fixedJson.replace(/```json\s*/gi, '').replace(/```/g, '');
        // Try to close unclosed arrays/objects
        const openBrackets = (fixedJson.match(/\[/g) || []).length - (fixedJson.match(/\]/g) || []).length;
        const openBraces = (fixedJson.match(/\{/g) || []).length - (fixedJson.match(/\}/g) || []).length;
        for (let i = 0; i < openBrackets; i++) fixedJson += ']';
        for (let i = 0; i < openBraces; i++) fixedJson += '}';
        // Remove trailing comma before closing brackets
        fixedJson = fixedJson.replace(/,\s*([}\]])/g, '$1');
        parsed = JSON.parse(fixedJson);
        console.log('[Summarizer] JSON parse attempt 2 succeeded (auto-closed brackets)');
      } catch (parseErr2) {
        console.warn('[Summarizer] JSON parse attempt 2 failed:', (parseErr2 as Error).message);
      }
    }

    // Attempt 3: Extract what we can with regex
    if (!parsed) {
      console.warn('[Summarizer] All JSON parse attempts failed, extracting manually');
      const highlightMatch = responseText.match(/"highlights"\s*:\s*\[(.*?)\]/s);
      const highlights = highlightMatch
        ? highlightMatch[1].match(/"([^"]+)"/g)?.map(s => s.replace(/"/g, '')) ?? []
        : ['Conversation summary (auto-extracted)'];

      parsed = {
        highlights,
        hardStickNotes: [],
        actionItems: [],
        filesReferenced: [],
        estimatedTimeSpent: 0,
      };
    }

    return {
      highlights: parsed.highlights || [],
      hardStickNotes: parsed.hardStickNotes || [],
      actionItems: parsed.actionItems || [],
      filesReferenced: parsed.filesReferenced || [],
      estimatedTimeSpent: parsed.estimatedTimeSpent || 0,
    };
  } catch (e) {
    console.error('[Summarizer] Haiku error:', e);
    // Return empty structure on error, don't crash
    return {
      highlights: ['[Summary generation failed]'],
      hardStickNotes: [],
      actionItems: [],
      filesReferenced: [],
      estimatedTimeSpent: 0,
    };
  }
}
// ─────────────────────────────────────────────────────────────
// KNOWLEDGE GRAPH NODE EXTRACTION (Simple)
// ─────────────────────────────────────────────────────────────

function extractKGNodes(messages: ConversationMessage[]): string[] {
  // Simple extraction: look for capitalized words that might be concepts
  const text = messages.map(m => m.content).join(' ');
  
  // Find capitalized phrases (2-3 word noun phrases)
  const regex = /\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b/g;
  const matches = text.match(regex) || [];
  
  // Filter common words and deduplicate
  const stopWords = new Set(['The', 'A', 'An', 'And', 'Or', 'But', 'Is', 'Are', 'Was', 'Were']);
  const nodes = [...new Set(matches)]
    .filter(m => !stopWords.has(m) && m.length > 2)
    .slice(0, 10); // limit to 10 nodes
  
  return nodes;
}

// ─────────────────────────────────────────────────────────────
// MAIN SUMMARIZATION FUNCTION
// ─────────────────────────────────────────────────────────────

export async function summarizeConversation(
  conversationId: string,
  messages: ConversationMessage[],
  apiKey: string
): Promise<ConversationSummary> {
  if (messages.length === 0) {
    throw new Error('No messages to summarize');
  }

  const summaryData = await generateSummaryData(messages, apiKey);
  const subject = detectSubject(messages);
  const kgNodes = extractKGNodes(messages);

  const summary: ConversationSummary = {
    id: `summary_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
    conversationId,
    date: new Date().toISOString(),
    subject,
    highlights: summaryData.highlights,
    hardStickNotes: summaryData.hardStickNotes,
    actionItems: summaryData.actionItems,
    filesReferenced: summaryData.filesReferenced,
    knowledgeGraphNodes: kgNodes,
    estimatedTimeSpent: summaryData.estimatedTimeSpent,
    messageCount: messages.length,
    pinnedForReview: false,
    userTags: [],
  };

  return summary;
}

// ─────────────────────────────────────────────────────────────
// STORAGE OPERATIONS
// ─────────────────────────────────────────────────────────────

export async function storeSummary(summary: ConversationSummary): Promise<void> {
  const db = await getDatabase();
  
  await db.runAsync(
    `INSERT INTO conversation_summaries (
      id, conversation_id, date, subject,
      highlights, hard_stick_notes, action_items,
      files_referenced, kg_nodes, time_spent, message_count,
      pinned, user_tags
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      summary.id,
      summary.conversationId,
      summary.date,
      summary.subject,
      JSON.stringify(summary.highlights),
      JSON.stringify(summary.hardStickNotes),
      JSON.stringify(summary.actionItems),
      JSON.stringify(summary.filesReferenced),
      JSON.stringify(summary.knowledgeGraphNodes),
      summary.estimatedTimeSpent,
      summary.messageCount,
      summary.pinnedForReview ? 1 : 0,
      JSON.stringify(summary.userTags),
    ]
  );

  console.log('[Summarizer] Stored summary:', summary.id, summary.subject);
}
// ─────────────────────────────────────────────────────────────
// QUERY OPERATIONS
// ─────────────────────────────────────────────────────────────

export async function getSummariesByDate(
  startDate: string,
  endDate: string
): Promise<ConversationSummary[]> {
  const db = await getDatabase();
  
  const results = await db.getAllAsync(
    `SELECT * FROM conversation_summaries 
     WHERE date BETWEEN ? AND ?
     ORDER BY date DESC`,
    [startDate, endDate]
  );

  return results.map((row: SummaryRow) => ({
    id: row.id,
    conversationId: row.conversation_id,
    date: row.date,
    subject: row.subject,
    highlights: JSON.parse(row.highlights || '[]'),
    hardStickNotes: JSON.parse(row.hard_stick_notes || '[]'),
    actionItems: JSON.parse(row.action_items || '[]'),
    filesReferenced: JSON.parse(row.files_referenced || '[]'),
    knowledgeGraphNodes: JSON.parse(row.kg_nodes || '[]'),
    estimatedTimeSpent: row.time_spent,
    messageCount: row.message_count,
    pinnedForReview: row.pinned === 1,
    userTags: JSON.parse(row.user_tags || '[]'),
    keepUntil: row.keep_until,
    archivedToCloud: row.archived_to_cloud,
  }));
}

export async function getSummariesBySubject(subject: string): Promise<ConversationSummary[]> {
  const db = await getDatabase();
  
  const results = await db.getAllAsync(
    `SELECT * FROM conversation_summaries 
     WHERE subject = ?
     ORDER BY date DESC`,
    [subject]
  );

  return results.map((row: SummaryRow) => ({
    id: row.id,
    conversationId: row.conversation_id,
    date: row.date,
    subject: row.subject,
    highlights: JSON.parse(row.highlights || '[]'),
    hardStickNotes: JSON.parse(row.hard_stick_notes || '[]'),
    actionItems: JSON.parse(row.action_items || '[]'),
    filesReferenced: JSON.parse(row.files_referenced || '[]'),
    knowledgeGraphNodes: JSON.parse(row.kg_nodes || '[]'),
    estimatedTimeSpent: row.time_spent,
    messageCount: row.message_count,
    pinnedForReview: row.pinned === 1,
    userTags: JSON.parse(row.user_tags || '[]'),
    keepUntil: row.keep_until,
    archivedToCloud: row.archived_to_cloud,
  }));
}

export async function getAllSummaries(): Promise<ConversationSummary[]> {
  const db = await getDatabase();
  
  const results = await db.getAllAsync(
    `SELECT * FROM conversation_summaries ORDER BY date DESC`
  );

  return results.map((row: SummaryRow) => ({
    id: row.id,
    conversationId: row.conversation_id,
    date: row.date,
    subject: row.subject,
    highlights: JSON.parse(row.highlights || '[]'),
    hardStickNotes: JSON.parse(row.hard_stick_notes || '[]'),
    actionItems: JSON.parse(row.action_items || '[]'),
    filesReferenced: JSON.parse(row.files_referenced || '[]'),
    knowledgeGraphNodes: JSON.parse(row.kg_nodes || '[]'),
    estimatedTimeSpent: row.time_spent,
    messageCount: row.message_count,
    pinnedForReview: row.pinned === 1,
    userTags: JSON.parse(row.user_tags || '[]'),
    keepUntil: row.keep_until,
    archivedToCloud: row.archived_to_cloud,
  }));
}

export async function updateSummary(
  summaryId: string,
  patch: Partial<ConversationSummary>
): Promise<void> {
  const db = await getDatabase();
  
  const updates: string[] = [];
  const values: any[] = [];

  if (patch.pinnedForReview !== undefined) {
    updates.push('pinned = ?');
    values.push(patch.pinnedForReview ? 1 : 0);
  }
  if (patch.userTags !== undefined) {
    updates.push('user_tags = ?');
    values.push(JSON.stringify(patch.userTags));
  }
  if (patch.keepUntil !== undefined) {
    updates.push('keep_until = ?');
    values.push(patch.keepUntil);
  }
  if (patch.archivedToCloud !== undefined) {
    updates.push('archived_to_cloud = ?');
    values.push(patch.archivedToCloud);
  }

  if (updates.length === 0) return;

  values.push(summaryId);
  await db.runAsync(
    `UPDATE conversation_summaries SET ${updates.join(', ')} WHERE id = ?`,
    values
  );

  console.log('[Summarizer] Updated summary:', summaryId);
}

export async function deleteSummary(summaryId: string): Promise<void> {
  const db = await getDatabase();

  await db.runAsync(
    'DELETE FROM conversation_summaries WHERE id = ?',
    [summaryId]
  );

  console.log('[Summarizer] Deleted summary:', summaryId);
}

/**
 * Scrub sensitive phrases from all summaries.
 * Removes matching entries from highlights and hardStickNotes arrays.
 * Call once on app init — safe to run multiple times.
 */
export async function scrubSummaries(phrases: string[]): Promise<number> {
  const db = await getDatabase();
  const all = await getAllSummaries();
  let scrubbed = 0;

  for (const s of all) {
    const origHighlights = s.highlights;
    const origNotes = s.hardStickNotes;

    const newHighlights = origHighlights.filter(
      h => !phrases.some(p => h.toLowerCase().includes(p.toLowerCase()))
    );
    const newNotes = origNotes.filter(
      n => !phrases.some(p => n.toLowerCase().includes(p.toLowerCase()))
    );

    if (newHighlights.length !== origHighlights.length || newNotes.length !== origNotes.length) {
      await db.runAsync(
        `UPDATE conversation_summaries SET highlights = ?, hard_stick_notes = ? WHERE id = ?`,
        [JSON.stringify(newHighlights), JSON.stringify(newNotes), s.id]
      );
      scrubbed++;
      console.log(`[Summarizer] Scrubbed summary ${s.id}`);
    }
  }

  console.log(`[Summarizer] Scrub complete: ${scrubbed} summaries cleaned`);
  return scrubbed;
}